site_name: "ML4Earth"
site_description: 'Machine Learning for Earth Science'
site_author: 'Weiqiang Zhu'
repo_name: 'ML4Earth'
# repo_url: 'https://github.com/ai4eps'
# edit_url: 'https://github.com/ai4eps/ai4eps.github.io/edit/master/classes/ml4earth/docs'
# edit_url: '/edit/master/classes/ml4earth/docs/'
nav:
    - Overview: README.md
    - Syllabus: syllabus.md
    - Standard Formats:
      - Seismic Data (one single file): seismic_event_format1.md
      - Seismic Data (one event per file): seismic_event_format2.md
      - DAS Data (one event per file): seismic_event_format_das.md
theme:
  name: 'material'
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
